# Generated by Django 3.0.5 on 2020-10-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_code',
        ),
    ]
