# Generated by Django 3.0.5 on 2020-10-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20201006_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='role',
        ),
    ]
