# Generated by Django 3.0.5 on 2020-10-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20201006_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SlugField(choices=[('USR', 'User'), ('MOD', 'Moderator'), ('ADM', 'Admin')], default='USR', max_length=3),
        ),
    ]
