# Generated by Django 3.0.5 on 2020-10-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_auto_20201006_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='bio',
        ),
    ]
