# Generated by Django 3.0.5 on 2020-10-09 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20201009_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2020)],
                verbose_name='Year'),
        ),
    ]
