# Generated by Django 3.0.5 on 2020-10-07 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201006_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date published'),
        ),
    ]
