# Generated by Django 3.0.5 on 2020-10-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201001_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['-id']},
        ),
    ]
