# Generated by Django 3.0.5 on 2020-10-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201001_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
