# Generated by Django 3.0.5 on 2020-10-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_titles_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
