# Generated by Django 3.0.5 on 2020-10-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_titles_rating'),
        ('api', '0014_remove_titles_rating'),
    ]

    operations = [
    ]
