POST     http://127.0.0.1:8000/api/v1/titles/1/reviews/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjAxODkxNzUxLCJqdGkiOiIyODlmM2ZlZGY5ZGM0MGM2ODhiYThkZGQzYTVlZjk3NCIsInVzZXJfaWQiOjJ9.7C2K15U-IqTRHRR5FYsLuGeKrK5lfRsd2IhdHkMBUNo



{
  "text": 
    "огонь"
  ,
  "score": 
    "8"
  
}